# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
Author.create(username: 'author1', email: 'author1@example.com', password: 'password', password_confirmation: 'password', role: ADMIN)
User.create(username: 'user1', email: 'user1@example.com', password: 'password', password_confirmation: 'password', role: USER)
Category.create(title: 'Social Media')
  Category.create(title: 'Facebook', parent_category_id: 1)
  Category.create(title: 'Google+', parent_category_id: 1)
  Category.create(title: 'How To', parent_category_id: 1)
  Category.create(title: 'Twitter', parent_category_id: 1)
  Category.create(title: 'YouTube', parent_category_id: 1)
Category.create(title: 'Tech')
  Category.create(title: 'Apps and Software', parent_category_id: 7)
  Category.create(title: 'Dev & Design', parent_category_id: 7)
  Category.create(title: 'Gadgets', parent_category_id: 7)
  Category.create(title: 'Mobile', parent_category_id: 7)
Category.create(title: 'Business')
  Category.create(title: 'Advertising', parent_category_id: 12)
  Category.create(title: 'Jobs', parent_category_id: 12)
  Category.create(title: 'Marketing', parent_category_id: 12)
  Category.create(title: 'Media', parent_category_id: 12)
  Category.create(title: 'Small Business', parent_category_id: 12)
  Category.create(title: 'Startups', parent_category_id: 12)
Category.create(title: 'Entertainment')
  Category.create(title: 'Film', parent_category_id: 19)
  Category.create(title: 'Gaming', parent_category_id: 19)
  Category.create(title: 'Music', parent_category_id: 19)
  Category.create(title: 'Sports', parent_category_id: 19)
  Category.create(title: 'Television', parent_category_id: 19)
Tag.create(title: 'tag1')
Tag.create(title: 'tag2')
Tag.create(title: 'tag3')
Tag.create(title: 'tag4')
author = Author.find_by_email('author1@example.com')
Blog.create(title: 'test blog 1', description: 'this is my first blog', author_id: author.id, category_id: 1).tags << Tag.find_by_id(1)
Blog.create(title: 'test blog 2', description: 'this is my second blog', author_id: author.id, category_id: 7).tags << Tag.find_by_id(2)
Blog.create(title: 'test blog 3', description: 'this is my third blog', author_id: author.id, category_id: 12).tags << Tag.find_by_id(3)
Blog.create(title: 'test blog 4', description: 'this is my fourth blog', author_id: author.id, category_id: 19).tags << Tag.find_by_id(4)
